### ISSUE TITLE
Allow bidirectional communication 

### ISSUE THREAD

**Issue by provanshu** [aws-solutions/media-exchange-on-aws#15]
**Is your feature request related to a problem? Please describe.**
In current design, if a subscriber has to return assets back to the publisher, they would have to be onboarded as another publisher. This is complex to manage. 

**Describe the feature you'd like**
Please provide an option to create a return path in mediaexchange for publisher -> subscriber -> publisher

**Comment by raulmlamzn** [comment]
Thank you for your suggestion @provanshu. We've carefully considered your feedback and have decided not to include this feature in a future release.
