### ISSUE TITLE
Delivery receipts and automatically delete the assets from mediaexchange 

### ISSUE THREAD

**Issue by provanshu** [aws-solutions/media-exchange-on-aws#16]
**Is your feature request related to a problem? Please describe.**
In the current design, the there is no explicit delivery receipt. If there was a notion of a delivery receipt, the publisher can automatically delete the assets from the mediaexchange bucket, thereby reducing cost. 

**Describe the feature you'd like**
- introduce delivery receipts routing in MediaExchange subscriber-> publisher
- add delivery receipts to autoingest tool 
- new tool for deleting assets based on delivery receipt. 

**Additional context**

**Comment by raulmlamzn** [comment]
Thanks for your suggestion @provanshu. We considered your feedback and added this request to our backlog for the solution.
