### ISSUE TITLE
Documentation : IAM policy needed for subscriber’s IAM role for automated testing.

### ISSUE THREAD

**Issue by gmarchand** [aws-solutions/media-exchange-on-aws#26]
**Describe the bug**
I don't know what policies needed for subscriber / publisher's IAM role for automated testing.
1. Could you explain what does automated testing mean ? 
2. Could you share a code snippet of the subscriber and publiser's role ?

**To Reproduce**

Read the doc : https://docs.aws.amazon.com/solutions/latest/media-exchange-on-aws/step-2.-add-publishers-and-subscribers.html

- [x] Version: 1.2.1
To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "(SO0133) - media-exchange-on-aws v1.1.0. You can also find the version from [releases](https://github.com/aws-solutions/media-exchange-on-aws/releases).
- [ ] Region: [e.g. us-east-1]
- [x] Was the solution modified from the version published on this repository? NO
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs? NO

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
<img width="1305" alt="image" src="https://github.com/aws-solutions/media-exchange-on-aws/assets/308444/0e149ff8-4dc3-4b49-8a15-35682731d36c">

**Additional context**

**Comment by raulmlamzn** [comment]
Hello gmarchand,
Thanks for your feedback. We are currently reviewing this with our engineering team.

**Comment by amzn-gaod** [comment]
Hi gmarchand

This solution is no longer being maintained and we are closing this bug ticket as a result.
