### ISSUE TITLE
Emails don't support '+'

### ISSUE THREAD

**Issue by provanshu** [aws-solutions/media-exchange-on-aws#7]
**Describe the bug**
Email addresses in the cloudformation templates does not support '+' sign.

**To Reproduce**
I tried using dilisant+mediaopos@amazon.com as Owner email and it does not like "+" in email.

**Expected behavior**

**Please complete the following information about the solution:**

- [x] Version: [e.g. v1.0.0]
- [x] Region: [e.g. us-east-1]
- [x] Was the solution modified from the version published on this repository?
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by e-thoman** [comment]
Hello! This was fixed in a prior update (alongside the cdk conversion)
