### ISSUE TITLE
AutoIngest Tool - Cloudformation Bad description

### ISSUE THREAD

**Issue by gmarchand** [aws-solutions/media-exchange-on-aws#8]
**Describe the bug**
The description of the parameter is not the good one as you can see : 
https://github.com/awslabs/media-exchange-on-aws/blob/master/tools/autoingest/deployment/autoingest.yaml#L63
https://github.com/awslabs/media-exchange-on-aws/blob/master/tools/autoingest/deployment/autoingest.yaml#L59

**Expected behavior**
it's hard to understand which format is expected. 
It's hard to understand how the Lambda function is assuming a cross account role to the source bucket : https://raw.githubusercontent.com/awslabs/media-exchange-on-aws/master/tools/autoingest/images/autoingest.jpeg
How could I assume a role ?

**Comment by raulmlamzn** [comment]
Hello @gmarchand,
Thanks for your feedback. Let me know if this is still an issue for you and we can review it with our engineering team
